### ISSUE TITLE
Update tegrasign to python3

### ISSUE THREAD

**Issue by nvl1109** [madisongh/digsigserver#11]
Hi, in master branch of meta-tegra, the tegraxxx-flashtools-native was upgraded to python3 (https://github.com/OE4T/meta-tegra/blob/master/recipes-bsp/tegra-binaries/tegra-flashtools-native_35.1.0.bb#L9-L11). But digsigserver tegrasign is still using python2.

Please update digsigserver to python3 also?

**Comment by madisongh** [comment]
You could apply those same patches to the installation of the NVIDIA tools you use with digsigserver.  What I do on my signing server is to install both python 2 and 3, and configure the system to point `/usr/bin/python` to point to `python2`, to emulate the old Ubuntu environment that the NVIDIA tools expect.  On Ubuntu 22.04, I use
```
$ sudo apt install python2
$ update-alternatives --install /usr/bin/python python /usr/bin/python2 1
```

BTW, I haven't actually done much testing with the L4T R35.1.0 tools, so other issues may arise.

**Comment by nvl1109** [comment]
I agree to that using `python` & `update-alternatives` is more flexible. Was updated in my fork. Thank you.
