### ISSUE TITLE
Signing Error

### ISSUE THREAD

**Issue by Rsaliu** [madisongh/digsigserver#16]
@madisongh 

I managed to setup the Docker container and connected to it successfully as described in the readme. However, the sigining did not complete, I get the following error.

Type ? or help for help and q or quit to exit
Use ! to execute system commands
 
[   0.0021 ] Using default ramcode: 0
[   0.0021 ] Disable BPMP dtb trim, using default dtb
[   0.0021 ] 
[   0.0045 ] tegrasign --getmode mode.txt --key /tmp/tmpgwvkoq82/rsa_priv.pem
[   0.0057 ] PKC key in Open SSL format
[   0.0059 ] Key size is 256 bytes
[   0.0068 ] 
[   0.0069 ] Generating RCM messages
[   0.0090 ] tegrarcm --listrcm rcm_list.xml --chip 0x21 0 --download rcm nvtboot_recovery.bin 0 0
[   0.0097 ] RCM 0 is saved as rcm_0.rcm
[   0.0101 ] RCM 1 is saved as rcm_1.rcm
[   0.0103 ] List of rcm files are saved in rcm_list.xml
[   0.0103 ] 
[   0.0103 ] Signing RCM messages
[   0.0121 ] tegrasign --key /tmp/tmpgwvkoq82/rsa_priv.pem --list rcm_list.xml --pubkeyhash pub_key.key
[   0.0127 ] PKC key in Open SSL format
[   0.0129 ] Key size is 256 bytes
[   0.0129 ] Saving public key  in pub_key.key
[   0.0842 ] Saving public key Hash as binary: pub_key.hash
[   0.0842 ] Saving public key Hash as big-endian text: pub_key.hash_txt
[   0.0842 ] Saving public key Hash as little-endian(sysfs) text: pub_key.hash_sysfs_txt
[   0.0842 ] 
[   0.0842 ] Copying signature to RCM mesages
[   0.0867 ] tegrarcm --chip 0x21 0 --updatesig rcm_list_signed.xml --pubkeyhash pub_key.key
[   0.0893 ] 
[   0.0893 ] Parsing partition layout
[   0.0912 ] tegraparser --pt flash.xml.tmp
[   0.0923 ] 
[   0.0923 ] Creating list of images to be signed
[   0.0942 ] tegrahost --chip 0x21 0 --partitionlayout flash.xml.bin --list images_list.xml
[   0.0949 ] File TBCFILE open failed
[   0.0951 ] Stat for TBCFILE failed
[   0.0951 ] 
Error: Return value 4
Command tegrahost --chip 0x21 0 --partitionlayout flash.xml.bin --list images_list.xml

2023-06-22 04:01:25,108-722-DEBUG-stderr: cp: cannot stat 'signed/*': No such file or directory

Any help will be greatly appreciated.

Thanks,

**Comment by madisongh** [comment]
Can you provide more info on
* what machine you're targeting
* which version of L4T are you using

and maybe attach a log with the logging level set to debug?

From the mention of  `TBCFILE` in the log you posted, [these lines](https://github.com/OE4T/meta-tegra/blob/3ffb940d617d5021acf0fcfcc7a7689328fec42e/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra210-flash-helper.sh#L305-L306) in the t210 helper script (that link to the L4T R32.7.x helper) didn't get run?

**Comment by madisongh** [comment]
>  that is how i got the log I posted above.

But that wasn't the complete log, just a fragment. It would help to see the complete log, from when the POST was received through to the reply that was sent back.

**Comment by madisongh** [comment]
I've attached a log for a Nano signing I just ran from a build out of [my test distro](https://github.com/madisongh/tegra-test-distro/tree/kirkstone-l4t-r32.7.x) for your reference

file:///home/madison/Downloads/digsig.log

**Comment by madisongh** [comment]
I think the problem might be that the docker configuration is based off the meta-tegra `dunfell` branch, but you're trying to use the signing server with meta-tegra's kirkstone-l4t-r32.7.x` branch.  There were some changes in that branch, and you'll need the `tegra210-flash-helper` script from there to be compatible.  I'm don't use Docker, so I don't know much about it, but it looks like it shouldn't be too hard to modify the Dockerfile to do this (and maybe simplify it a bit if you don't care about support for older versions of L4T, which aren't supported in that meta-tegra branch anyway).

**Comment by Rsaliu** [comment]
> I think the problem might be that the docker configuration is based off the meta-tegra `dunfell` branch, but you're trying to use the signing server with meta-tegra's kirkstone-l4t-r32.7.x`branch. There were some changes in that branch, and you'll need the`tegra210-flash-helper` script from there to be compatible. I don't use Docker, so I don't know much about it, but it looks like it shouldn't be too hard to modify the Dockerfile to do this (and maybe simplify it a bit if you don't care about support for older versions of L4T, which aren't supported in that meta-tegra branch anyway).

Thanks for your response @madisongh .  Yes, my build is from kirkstone-l4t-r32.7.x`branch, I will make the necessary changes and revert.

Thanks

**Comment by madisongh** [comment]
Great.  If you get something working, would you be willing to submit a PR for it, maybe as an additional Dockerfile?

**Comment by Lexmark-chad** [comment]
I've logged a separate issue for coming up with a more generalizable solution that will make it easier to keep pace with newer L4T releases (or adding support for older releases).

https://github.com/madisongh/digsigserver/issues/18

I'll try to find time to work on this.
