### ISSUE TITLE
Using HSM for i.MX signing

### ISSUE THREAD

**Issue by pboucherat-thegoodpenguin** [madisongh/digsigserver#22]
We've just done some work for customer on using a YubiHSM 2 token for i.MX code signing using digsigserver. The customer is keen to upstream this so I can submit a PR if you would be interested in seeing this. Although this was specifically for the YubiHSM 2, this just means that the docker image contains the YubiHSM support, but the actual signing bits use pkcs11 and are therefore generally applicable to any HSM that supports pkcs11. Please let me know if you're interested.

**Comment by pboucherat-thegoodpenguin** [comment]
Brilliant, just trying to get it through a code review over here first ... but should submit it sometime today or tomorrow.

**Comment by pboucherat-thegoodpenguin** [comment]
see https://github.com/madisongh/digsigserver/pull/23

**Comment by madisongh** [comment]
Merged #23 , thanks!
