### ISSUE TITLE
generation of kernel signing keys

### ISSUE THREAD

**Issue by outbackdingo** [madisongh/digsigserver#4]
ok enlightenment needed, how are you generating ? openssl ?
${DIGSIGSERVER_KEYFILE_URI}/${machine}/kmodsign/kernel-signkey.priv
${DIGSIGSERVER_KEYFILE_URI}/${machine}/kmodsign/kernel-signkey.x509

**Comment by madisongh** [comment]
Yes, openssl, per the instructions in [the kernel documentation](https://github.com/OE4T/linux-tegra-4.9/blob/patches-l4t-r32.4/Documentation/module-signing.txt).

**Comment by outbackdingo** [comment]
yeah, i did that, sorry it was a permissions error, fixed  now. thanks
